### ISSUE TITLE
zabbix_IIS_checker.py, pycurl.error: cannot invoke setopt() - no curl handle

### ISSUE THREAD

**Issue by pbychikhin** [pbychikhin/utils#6]
zabbix_IIS_checker.py ver. 1.1-5-g3db6579

C:\zabbix_agents\py_scripts>py -3 zabbix_IIS_checker.py
Exception in thread Checker:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 911, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "zabbix_IIS_checker.py", line 651, in run
    for probe_info in executor.map(self.get_site_probe, (site for site in self._IIS_sites.get() if site.get_name() in sites_started))
:
  File "C:\Python34\lib\concurrent\futures\_base.py", line 549, in result_iterator
    yield future.result()
  File "C:\Python34\lib\concurrent\futures\_base.py", line 395, in result
    return self.__get_result()
  File "C:\Python34\lib\concurrent\futures\_base.py", line 354, in __get_result
    raise self._exception
  File "C:\Python34\lib\concurrent\futures\thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "zabbix_IIS_checker.py", line 567, in get_site_probe
    c.setopt(pycurl.WRITEDATA, buffer)
pycurl.error: cannot invoke setopt() - no curl handle

**Comment by pbychikhin** [comment]
CURL close() method was being called too early. So that multistage check could not set option on closed handle.
Fixed - moved close() to the "finally" block embracing entire probing loop.

**Comment by pbychikhin** [comment]
Fixed in 52afdb2
